openapi: 3.1.0
servers:
  - url: http://juicer.local
info:
  title: jesus juicer
  version: 0.0.3
  description: Api schema of jesus juicer device
  contact:
    name: John Cuba
    email: ekubetsky@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /api:
    options:
      security: []
      summary: preflight request
      operationId: preflightRequest
      responses:
        200:
          $ref: "#/components/responses/Ok"
        400:
          $ref: "#/components/responses/Bad"
  /api/wifi/ap:
    get:
      security: []
      tags:
        - ap
        - wifi
      summary: get ap credentials
      parameters: []
      operationId: getApCredentials
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/wifiCredentials"
          description:
            The request was successful, and the server has returned the
            requested resource in the response body.
        400:
          $ref: "#/components/responses/Bad"
    patch:
      security: []
      tags:
        - ap
        - wifi
      summary: set ap credentials
      operationId: setApCredentials
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/wifiCredentials"
        required: true
        description: ""
      responses:
        200:
          $ref: "#/components/responses/Ok"
        400:
          $ref: "#/components/responses/Bad"
  /api/wifi/state:
    get:
      security: []
      tags:
        - wifi
      summary: get wifi state
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                title: GetWifiStateOk
                required:
                  - mode
                  - ip
                  - rssi
                properties:
                  ip:
                    type: string
                  mode:
                    $ref: "#/components/schemas/wifiMode"
                  rssi:
                    type: number
          description:
            The request was successful, and the server has returned the
            requested resource in the response body.
        400:
          $ref: "#/components/responses/Bad"
      parameters: []
      operationId: getWifiState
  /api/wifi/network:
    get:
      security: []
      tags:
        - network
        - wifi
      summary: get network ap credentials
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/wifiCredentials"
          description:
            The request was successful, and the server has returned the
            requested resource in the response body.
        400:
          $ref: "#/components/responses/Bad"
      operationId: getNetworkApCredentials
    patch:
      security: []
      tags:
        - network
        - wifi
      summary: set network ap credentials
      operationId: setNetworkApCredentials
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/wifiCredentials"
        required: true
        description: ""
      responses:
        200:
          $ref: "#/components/responses/Ok"
        400:
          $ref: "#/components/responses/Bad"
    delete:
      security: []
      tags:
        - network
      summary: del network ap credentials
      operationId: delNetworkApCredentials
      responses:
        200:
          $ref: "#/components/responses/Ok"
        400:
          $ref: "#/components/responses/Bad"
  /api/tds:
    get:
      security: []
      operationId: getTdsSensorValue
      tags:
        - tds
      summary: Get tds sensor value
      responses:
        "200":
          description:
            The request was successful, and the server has returned the
            requested resource in the response body.
          content:
            text/plain:
              schema:
                type: string
                title: GetTdsSensorValueOk
        400:
          $ref: "#/components/responses/Bad"
  /api/update/fw:
    get:
      security: []
      operationId: getFirmwareVersion
      tags:
        - update
      summary: get firmware version
      responses:
        "200":
          description: The request was successful, and the server has returned firmware version.
          content:
            text/plain:
              schema:
                type: string
        400:
          $ref: "#/components/responses/Bad"
    post:
      security: []
      operationId: uploadFirmware
      tags:
        - update
      summary: upload firmware
      requestBody:
        required: true
        description: ""
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        200:
          $ref: "#/components/responses/Ok"
        400:
          $ref: "#/components/responses/Bad"

  /api/update/fs:
    post:
      security: []
      operationId: uploadFilesystem
      tags:
        - update
      summary: upload filesystem
      requestBody:
        required: true
        description: ""
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary

      responses:
        200:
          $ref: "#/components/responses/Ok"
        400:
          $ref: "#/components/responses/Bad"
components:
  schemas:
    wifiMode:
      oneOf:
        - enum:
            - "0"
            - "1"
            - "2"
            - "3"
          type: string
          default: "0"
      description: ""
    wifiCredentials:
      type: object
      required:
        - ssid
      properties:
        ssid:
          type: string
        password:
          type: string
      description:
        A simplified representation of a wifiCredentials, typically used in
        list views.
  responses:
    Ok:
      description: Successful operation.
      content:
        text/plain:
          schema:
            type: string
            example: "ok"
    Bad:
      description: Unsuccessful operation.
      content:
        text/plain:
          schema:
            type: string
            example: "bad"
tags:
  - name: wifi
    description: Manage wifi connection, by self AP or client mode
  - name: ap
    description: Manage config of self AP
  - name: network
    description: Manage config of wifi client mode
  - name: tds
    description: Manage TDS meter config
  - name: update
    description: Upload and flush firmware or data
