openapi: 3.1.0
info:
  title: Aquaphobic
  version: 0.0.0
  description: Api schema of aquaphobic device
  x-fiddle-import-file: true
paths:
  /api/wifi:
    options:
      tags:
        - wifi
      summary: preflight request
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: "null"
                title: PreflightRequestOk
          description: The request was successful, and the server has returned the
            requested resource in the response body.
      parameters: []
      operationId: preflightRequest
  /api/wifi/ap:
    get:
      tags:
        - ap
        - wifi
      summary: get ap credentials
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/wifiCredentials"
          description: The request was successful, and the server has returned the
            requested resource in the response body.
      parameters: []
      operationId: getApCredentials
    patch:
      tags:
        - ap
        - wifi
      summary: set ap credentials
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
                title: SetApCredentialsOk
          description: The request was successful, and the server has returned the
            requested resource in the response body.
      operationId: setApCredentials
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/wifiCredentials"
        required: true
        description: ""
  /api/wifi/state:
    get:
      tags:
        - wifi
      summary: get wifi state
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                required:
                  - mode
                  - ip
                  - rssi
                properties:
                  ip:
                    type: string
                  mode:
                    $ref: "#/components/schemas/wifiMode"
                  rssi:
                    type: number
                title: GetWifiStateOk
          description: The request was successful, and the server has returned the
            requested resource in the response body.
      parameters: []
      operationId: getWifiState
  /api/wifi/network:
    get:
      operationId: getNetworkApCredentials
      tags:
        - network
        - wifi
      summary: get network ap credentials
      responses:
        "200":
          description: The request was successful, and the server has returned the
            requested resource in the response body.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/wifiCredentials"
    patch:
      operationId: setNetworkApCredentials
      tags:
        - network
        - wifi
      summary: set network ap credentials
      responses:
        "200":
          description: The request was successful, and the server has returned the
            requested resource in the response body.
          content:
            text/plain:
              schema:
                type: string
      requestBody:
        required: true
        description: ""
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/wifiCredentials"
    delete:
      operationId: delNetworkApCredentials
      tags:
        - network
      summary: del network ap credentials
      responses:
        "200":
          description: The request was successful, and the server has returned the
            requested resource in the response body.
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    wifiMode:
      oneOf:
        - enum:
            - "0"
            - "1"
            - "2"
            - "3"
          type: string
          default: "0"
      description: ""
    wifiCredentials:
      type: object
      required:
        - ssid
      properties:
        ssid:
          type: string
        password:
          type: string
      description: A simplified representation of a wifiCredentials, typically used in
        list views.
    wifiCredentialsEdit:
      type: object
      required:
        - ssid
        - index
      properties:
        to:
          type: number
        ssid:
          type: string
        index:
          type: number
        password:
          type: string
      description: ""
      x-fiddle-dto-info:
        baseSchemaName: wifiCredentials
  responses:
    NotFound:
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
      description: The server cannot find the requested resource. The endpoint may be
        invalid or the resource may no longer exist.
    BadRequest:
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              errors:
                type: array
                items:
                  type: object
                  required:
                    - message
                  properties:
                    message:
                      type: string
              message:
                type: string
      description: The server could not understand the request due to invalid syntax.
        The client should modify the request and try again.
    Ok:
      description: The request was successful, and the server has returned the
        requested resource in the response body.
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
            required:
              - data
tags:
  - name: wifi
  - name: ap
  - name: network
