name: build

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: bump version
        run: |
          bash ./.github/workflows/bash/bump_version.sh "${{ github.event.release.name }}"

      - name: commit version bump
        uses: EndBug/add-and-commit@v9
        with:
          message: Bump version to ${{ github.event.release.name }}
          committer_name: GitHub Actions
          committer_email: actions@github.com
          new_branch: main

      - name: build frontend
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: |
          cd ./frontend
          bun install
          bun run build

      - name: set up Python
        uses: actions/setup-python@v1

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: install platformIO libraries
        run: pio lib install

      - name: build firmware & fs image
        run: |
          platformio run
          platformio run --target buildfs

      - name: upload assets to release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.event.release.name }} .pio/build/main/firmware.bin .pio/build/main/littlefs.bin
